languageCode: 'en-us'
title: 'Oliver Grosvenor-Newth'
theme: 'PaperMod'

params:
  author: 'Oliver Grosvenor-Newth'
  ShowReadingTime: true
  hideAuthor: true
  disableThemeToggle: true
  disableScrollToTop: true
  disableAnchoredHeadings: true

markup:
  goldmark:
    renderer:
      unsafe: true
