baseURL: https://newth.art
contentDir: 'content/newth.art'
publishDir: 'public/newth.art'
params:
  themeVarsCSS: 'css/core/theme-vars_newth_art.css'
  defaultTheme: dark
  description:
    "I'm Oliver, an immersive light artist creating large-scale illuminated installations for
    Burning Man, urban landscapes and public spaces."
  profileMode:
    enabled: true
    title: 'Creating immersive experiences that inspire awe.'
    subtitle:
      "I'm Oliver, an immersive light artist creating large-scale illuminated installations for
      Burning Man, urban landscapes and public spaces."
menu:
  main:
    - identifier: Projects
      name: Projects
      url: /projects/
      weight: 1
    - identifier: services
      name: Services
      url: /services/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
  footer:
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 1
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 2
    - identifier: ai
      name: AI and Product
      url: https://www.newth.ai/
      weight: 3
